"""initial schema - 43 tables

Revision ID: 8261c3862e5b
Revises: 
Create Date: 2026-04-15 01:32:53.728628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8261c3862e5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('usd_fx_rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('fintech_subverticals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risk_level'), nullable=False),
    sa.Column('regulatory_complexity', sa.Enum('low', 'medium', 'high', name='regulatory_complexity'), nullable=False),
    sa.Column('key_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('founders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('background', sa.Text(), nullable=True),
    sa.Column('nationality', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('funds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vintage_year', sa.Integer(), nullable=False),
    sa.Column('target_size_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deployed_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('geography_focus', sa.String(length=255), nullable=True),
    sa.Column('stage_focus', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('fundraising', 'investing', 'harvesting', 'closed', name='fund_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Enum('pre_seed', 'seed', 'series_a', 'series_b', name='market_stage'), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sourcing_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('network', 'accelerator', 'inbound', 'studio', 'event', 'cold', name='sourcing_channel_type'), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Enum('pre_seed', 'seed', 'series_a', 'series_b', 'bridge', name='startup_stage'), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('founded_at', sa.Date(), nullable=True),
    sa.Column('studio_built', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'exited', 'dead', 'watchlist', name='startup_status'), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('gp', 'analyst', 'studio_operator', 'viewer', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('insert', 'update', 'delete', name='audit_action'), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('multiple_type', sa.Enum('ARR', 'EV_Revenue', 'EBITDA', 'GMV', name='multiple_type'), nullable=False),
    sa.Column('p10', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('p25', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('p50', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('p75', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('p90', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['market_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('multiple_type', sa.String(length=100), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('median_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['market_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('identified', 'screening', 'dd', 'ic', 'invested', 'passed', 'watchlist', name='deal_status'), nullable=False),
    sa.Column('sourcing_channel_id', sa.UUID(), nullable=True),
    sa.Column('introduced_by', sa.String(length=255), nullable=True),
    sa.Column('identified_at', sa.Date(), nullable=False),
    sa.Column('screening_at', sa.Date(), nullable=True),
    sa.Column('dd_start_at', sa.Date(), nullable=True),
    sa.Column('ic_date', sa.Date(), nullable=True),
    sa.Column('decision', sa.String(length=255), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sourcing_channel_id'], ['sourcing_channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fintech_comparables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=True),
    sa.Column('comparable_name', sa.String(length=255), nullable=False),
    sa.Column('subvertical_id', sa.UUID(), nullable=True),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('arr_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('valuation_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('arr_multiple', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subvertical_id'], ['fintech_subverticals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fintech_unit_economics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('subvertical_id', sa.UUID(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subvertical_id'], ['fintech_subverticals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('calculation_date', sa.Date(), nullable=False),
    sa.Column('moic', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tvpi', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('dpi', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rvpi', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('irr', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('total_invested_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_fmv_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_realized_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('scenario_type', sa.Enum('base', 'high', 'downside', name='scenario_type'), nullable=False),
    sa.Column('moic_p25', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('moic_p50', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('moic_p75', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('irr_p25', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('irr_p50', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('irr_p75', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('dpi_projected', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tvpi_projected', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('run_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funding_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('round_type', sa.Enum('pre_seed', 'seed', 'series_a', 'series_b', 'bridge', name='round_type'), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pre_money_val', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('post_money_val', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('lead_investor', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('closed', 'announced', 'rumored', name='round_status'), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('individual', 'institutional', 'family_office', 'fund_of_funds', name='lp_type'), nullable=False),
    sa.Column('committed_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('called_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('distributed_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.Enum('monthly', 'quarterly', 'annual', name='period_type'), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlier_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('market_p25', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('market_p75', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('flag_type', sa.Enum('overvalued', 'undervalued', 'top_performer', 'underperformer', name='flag_type'), nullable=False),
    sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regulatory_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'mitigated', 'pending', name='regulatory_risk_status'), nullable=False),
    sa.Column('impact_level', sa.Enum('low', 'medium', 'high', 'critical', name='impact_level'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('ic_memo', 'lp_update', 'ppm', 'sourcing_deck', name='report_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'final', 'archived', name='report_status'), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('startup_founders',
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('founder_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('equity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['founder_id'], ['founders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('startup_id', 'founder_id'),
    sa.UniqueConstraint('startup_id', 'founder_id', name='uq_startup_founder')
    )
    op.create_table('studio_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('idea_date', sa.Date(), nullable=True),
    sa.Column('validation_date', sa.Date(), nullable=True),
    sa.Column('mvp_date', sa.Date(), nullable=True),
    sa.Column('pmf_date', sa.Date(), nullable=True),
    sa.Column('first_external_seed_date', sa.Date(), nullable=True),
    sa.Column('build_cost_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equity_retained_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('studio_support_level', sa.Enum('full', 'partial', 'accelerator', name='studio_support_level'), nullable=False),
    sa.Column('current_studio_phase', sa.Enum('idea', 'validation', 'mvp', 'first_revenue', 'pmf', 'seed', 'series_a_prep', name='studio_phase'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('startup_id')
    )
    op.create_table('valuation_distributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('p10', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('p25', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('p50', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('p75', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('p90', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['market_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('driver_type', sa.Enum('nrr', 'rule_of_40', 'growth_rate', 'ltv_cac', 'gross_margin', name='driver_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('benchmark_threshold', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('above_threshold', sa.Boolean(), nullable=False),
    sa.Column('premium_justified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alpha_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_company_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('studio_value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('market_benchmark', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('delta_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_alpha', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['studio_company_id'], ['studio_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('build_costs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_company_id', sa.UUID(), nullable=False),
    sa.Column('cost_type', sa.Enum('personnel', 'tech', 'ops', 'legal', 'marketing', 'capex', name='build_cost_type'), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['studio_company_id'], ['studio_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dd_checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('item_category', sa.Enum('team', 'product', 'market', 'financials', 'legal', 'tech', name='dd_item_category'), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'na', name='dd_item_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ic_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('invest', 'pass_', 'watchlist', name='ic_decision_type'), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=False),
    sa.Column('committee_members_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('data_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_opportunities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id')
    )
    op.create_table('ic_memos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Enum('invest', 'pass_', 'watchlist', name='ic_recommendation'), nullable=False),
    sa.Column('valuation_proposed', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('key_risks', sa.Text(), nullable=True),
    sa.Column('key_upside', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('fund_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pre_money_val', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('equity_pct', sa.Numeric(precision=7, scale=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('investment_type', sa.Enum('lead', 'co_invest', 'follow_on', name='investment_type'), nullable=False),
    sa.Column('follow_on_reserve_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['round_id'], ['funding_rounds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lp_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lp_id', sa.UUID(), nullable=False),
    sa.Column('preferred_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reporting_frequency', sa.Enum('monthly', 'quarterly', 'annual', name='reporting_frequency'), nullable=False),
    sa.Column('tier', sa.Enum('anchor', 'core', 'standard', name='lp_tier'), nullable=False),
    sa.Column('last_update_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lp_id'], ['lps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lp_id')
    )
    op.create_table('narrative_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('data_references_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studio_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('studio_company_id', sa.UUID(), nullable=False),
    sa.Column('milestone_type', sa.Enum('idea', 'validation', 'mvp', 'first_revenue', 'pmf', 'seed', 'series_a', name='milestone_type'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['studio_company_id'], ['studio_companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesis_alignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('thesis_dimension', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('startup_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=True),
    sa.Column('pre_money_val', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('arr_at_time', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('multiple_paid', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['funding_rounds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['market_segments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['startup_id'], ['startups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('multiple_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('valuation_event_id', sa.UUID(), nullable=False),
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('multiple_paid', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('market_p25', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('market_p50', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('market_p75', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('premium_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('verdict', sa.Enum('within_range', 'premium_justified', 'overvalued', 'undervalued', name='valuation_verdict'), nullable=False),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['market_segments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['valuation_event_id'], ['valuation_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multiple_analyses')
    op.drop_table('valuation_events')
    op.drop_table('thesis_alignments')
    op.drop_table('studio_milestones')
    op.drop_table('narrative_blocks')
    op.drop_table('lp_profiles')
    op.drop_table('investments')
    op.drop_table('ic_memos')
    op.drop_table('ic_decisions')
    op.drop_table('dd_checklists')
    op.drop_table('build_costs')
    op.drop_table('alpha_metrics')
    op.drop_table('valuation_drivers')
    op.drop_table('valuation_distributions')
    op.drop_table('studio_companies')
    op.drop_table('startup_founders')
    op.drop_table('reports')
    op.drop_table('regulatory_risks')
    op.drop_table('outlier_flags')
    op.drop_table('metric_snapshots')
    op.drop_table('lps')
    op.drop_table('funding_rounds')
    op.drop_table('fund_scenarios')
    op.drop_table('fund_metrics')
    op.drop_table('fintech_unit_economics')
    op.drop_table('fintech_comparables')
    op.drop_table('deal_opportunities')
    op.drop_table('benchmark_series')
    op.drop_table('benchmark_entries')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_table('startups')
    op.drop_table('sourcing_channels')
    op.drop_table('market_segments')
    op.drop_table('funds')
    op.drop_table('founders')
    op.drop_table('fintech_subverticals')
    op.drop_table('currencies')
    # ### end Alembic commands ###
